name = "sfeee"
uuid = "01f2f92b-3405-405a-929c-625651ab1548"
version = "0.1.0"
authors = ["advancehs <1019753743@qq.com>"]

[deps]
BlockDiagonals = "0a1fb500-61f7-11e9-3c65-f5ef3456f9f0"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
Calculus = "49dc2e85-a5d0-5ad3-a950-438e2897f1b9"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
DocumenterTools = "35a29f4d-8980-5a13-9543-d66fff28ecb8"
FLoops = "cc61a311-1640-44b5-9fba-1b764f453329"
ForneyLab = "9fc3f58a-c2cc-5bff-9419-6a294fefdca9"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
HypothesisTests = "09f84164-cd44-5f33-b23f-e6b0d136a0d5"
KahanSummation = "8e2b3108-d4c1-50be-a7a2-16352aec75c3"
LineSearches = "d3d80556-e9d4-5f37-9878-2ab0fcc64255"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MAT = "23992714-dd62-5051-b70f-ba57cb901cac"
NLSolversBase = "d41bc354-129a-5804-8e4c-c37616107c6c"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
PrettyTables = "08abe8d2-0d0c-5749-adfa-8a2ac140af0d"
QuadGK = "1fd47b50-473d-5c70-9696-f719f8f3bcdc"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
RowEchelon = "af85af4c-bcd5-5d23-b03a-a909639aa875"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
StatFiles = "1463e38c-9381-5320-bcd4-4134955f093a"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsFuns = "4c63d2b9-4356-54db-8cca-17b64c39e42c"
XLSX = "fdbf4ff8-1666-58a4-91e7-1b58723a45e0"

[compat]
BlockDiagonals = "0.2.0"
CSV = "0.10.15"
Calculus = "0.5.2"
DataFrames = "1.8.1"
DataStructures = "0.18.22"
Distributions = "0.25.123"
Documenter = "0.27.25"
DocumenterTools = "0.1.21"
FLoops = "0.2.2"
ForneyLab = "0.12.0"
ForwardDiff = "0.10.39"
HypothesisTests = "0.11.6"
KahanSummation = "0.3.1"
LineSearches = "7.6.0"
LinearAlgebra = "1.12.0"
MAT = "0.11.5"
NLSolversBase = "8.0.0"
Optim = "2.0.1"
PrettyTables = "3.2.3"
QuadGK = "2.11.2"
Random = "1.11.0"
RowEchelon = "0.2.1"
SpecialFunctions = "2.7.1"
StatFiles = "0.8.0"
Statistics = "1.11.1"
StatsFuns = "1.5.2"
XLSX = "0.10.4"
